### ISSUE TITLE
fix(core): PostgreSQL FK provisioning adds constraints across uuid↔text drift it has already detected; status planner cannot see the drift

### ISSUE THREAD

**Issue by willgriffin** [happyvertical/smrt#2608]
Title: fix(core): PostgreSQL FK provisioning adds constraints across uuid↔text drift it has already detected; status planner cannot see the drift

## Symptom
On a database whose parent `id` columns are still `text` (created before R11's native-uuid change) while newer reference columns are `uuid`, v0.43.10 `db:status` lists FK constraints as pending and `db:migrate` fails with SQLSTATE 42804 (`foreign key constraint cannot be implemented … incompatible types`) — blocking every later statement in the same migration and, downstream, any deploy that runs `db:migrate` in an init container.

Observed in willgriffin.dev (dev DB): `tags.parent_id uuid → tags.id text`, `assets.source_asset_id uuid → assets.id text`, `assets.folder_id text → folders.id uuid`, `oidc_profile_email_reservations.profile_id uuid → profiles.id text`, `users_cli_auth_approve_limits.user_id uuid → users.id text`, `facts.previous_fact_id uuid → facts.id text`. The manifest declares **UUID on both sides** for all of them — so this is DB drift from R11, not a model error. Four other newly-emitted FKs are type-compatible and apply fine.

## Where the defect is (v0.43.10)
1. `packages/core/src/schema/schema-manager.ts` `ensurePostgresForeignKey()` (l.381–441): `resolvePostgresForeignKeyProbeOptions()` (l.443–475) already reads the live child/parent column types via `getTableSchema` and classifies the mismatch as `uuidCastSide: 'child' | 'parent' | 'both'` — but that result is used only to make the orphan probe cast. Execution then unconditionally runs `ALTER TABLE … ADD CONSTRAINT … FOREIGN KEY … NOT VALID` (l.433–437), which cannot succeed when the physical types differ (no cast is possible in FK DDL). Introduced by the #2540/#2552 change from `ensurePostgresDeferredForeignKey` to `ensurePostgresForeignKey`; #2551 made the *probe* type-compatible but not the DDL decision.
2. `packages/core/src/migrations/generator.ts` (l.121) and `migrations/orchestrate.ts` (l.303) plan FKs via `planForeignKeyCreation()` (`schema/foreign-key-planner.ts` l.105) purely from the manifest, so `db:status` reports the constraint as pending with no way to warn about live-type incompatibility.
3. Root gap: the differ does not detect or plan the `text → uuid` conversion of legacy `id`/reference columns (`ALTER COLUMN … TYPE uuid USING …::uuid`), so a pre-R11 database never converges to the manifest and every future FK on those tables inherits the problem.

## Proposed
- **Guard (safety):** in `ensurePostgresForeignKey`, when the normalized live types differ (`uuidCastSide !== 'none'`), do not emit `ADD CONSTRAINT`; fail closed with a diagnostic naming both columns and their live types and the suggested repair, consistent with the existing orphan-row failure message. Thread the same live-type check into the status/plan path when a database is available so `db:status` reports "blocked: incompatible column types" instead of "pending".
- **Root cause (convergence):** teach the differ to detect `text` vs `UUID` drift on primary-key and FK columns and plan `ALTER TABLE … ALTER COLUMN … TYPE uuid USING …::uuid`, gated by a probe that every existing value is uuid-shaped (reuse the `~*` uuid pattern the probe already has) and ordered before dependent FK statements. Document the one-time conversion for pre-R11 databases.
- **Tests:** `schema/issue-2413-foreign-keys.test.ts` gains a mixed-type case (child uuid / parent text and the reverse) asserting no `ADD CONSTRAINT` is executed and the diagnostic is raised; a differ test for the id type drift plan; a status test showing the blocked reason.

## Acceptance
- No `ADD CONSTRAINT … FOREIGN KEY` is attempted when live column types are incompatible; the failure names the columns and repair.
- `db:status` distinguishes "pending" from "blocked: incompatible types".
- A legacy `text`-id database converges to the manifest's `UUID` through a planned, probed migration, after which the FKs apply.
- Downstream: willgriffin/willgriffin.dev#419 (bump to 0.43.10 blocked at migrate) unblocks without app-side workarounds.

**Comment by willgriffin** [comment]
```json
{"branch": "codex/2608-fk-uuid-text-drift", "claimed_at": "2026-09-02T01:15:38Z", "heartbeat_at": "2026-09-02T01:32:22Z", "lease_seconds": 14400, "owner": "willgriffin", "release_evidence_sha256": "4a7801c298d369b9a6d05a37cf973ee97a078b1d39e724b172fe9bc448262374", "release_message": "Implementation claim released by `claude` session `smrt-2608-fk-uuid-text-drift` (review).", "release_pr_heads": {"2611": "17b25cd3a06e6faac3ea3827de0bad8f28ad3e08"}, "release_reason": "review", "released_at": "2026-09-02T01:44:39Z", "runtime": "claude", "schema": "hv-agent-claim:v1", "session": "smrt-2608-fk-uuid-text-drift", "worktree": "/Users/will/Work/_trees/smrt/fk-uuid-text-drift"}
```

**Comment by willgriffin** [comment]
```json
{"claim_comment_id": "IC_kwDOQDruXs8AAAABR_8ATQ", "heartbeat_at": "2026-09-02T01:32:21.157490Z", "schema": "hv-agent-heartbeat:v1", "session": "smrt-2608-fk-uuid-text-drift"}
```

**Comment by willgriffin** [comment]
Implementation claim released by `claude` session `smrt-2608-fk-uuid-text-drift` (review).

**Comment by willgriffin** [comment]
```json
{"branch": "codex/2608-fk-uuid-text-drift", "claimed_at": "2026-09-02T01:48:23.520248Z", "heartbeat_at": "2026-09-02T01:48:23.520283Z", "lease_seconds": 14400, "owner": "willgriffin", "project_status_before_claim": "Review", "release_reason": "race-lost", "released_at": "2026-09-02T02:08:12.135263Z", "runtime": "claude", "schema": "hv-agent-claim:v1", "session": "smrt-2608-resolve", "worktree": "/Users/will/Work/_trees/smrt/fk-uuid-text-drift"}
```

**Comment by willgriffin** [comment]
A later duplicate/race-lost claim cycle invalidates earlier review authority. Reacquire implementation, verify the current revision, and release a new cycle.

**Comment by willgriffin** [comment]
```json
{"branch": "codex/2608-fk-uuid-text-drift", "claimed_at": "2026-09-02T02:08:44.435326Z", "heartbeat_at": "2026-09-02T02:08:44.435356Z", "lease_seconds": 14400, "owner": "willgriffin", "project_status_before_claim": "Review", "runtime": "claude", "schema": "hv-agent-claim:v1", "session": "smrt-2608-resolve-2", "worktree": "/Users/will/Work/_trees/smrt/fk-uuid-text-drift"}
```

**Comment by willgriffin** [comment]
Blocked handoff (session limit, 2026-09-02T04:20Z). State: PR #2611 head advanced to 7702f7874 with two validated follow-up commits (fa13aa854 convergence robustness/ordering; 7702f7874 db:migrate create-table batch ordering) — smrt-core 4091 tests, smrt-cli 917 tests green locally; CI re-running. NOT DONE: the five review threads are still open with no replies — Codex P1 differ.ts:754 (populate column on convergence changes), Codex P1 orchestrate.ts:317 (convergence before new-table DDL), Codex P2 differ.ts:651 (orphan tables before planning), Copilot differ.ts:1009 and schema-manager.ts:445 (UUID-specific repair text on non-UUID relationships). The two pushed commits were written against those threads but each still needs a per-thread reply + resolve, and the live-PostgreSQL optional lane should be re-run on the new head. Resume: claim, run the resolve flow on PR #2611, confirm CI + lifecycle green, release.

**Comment by willgriffin** [comment]
```json
{"branch": null, "claimed_at": "2026-09-02T04:21:24.493221Z", "heartbeat_at": "2026-09-02T04:21:24.493283Z", "lease_seconds": 14400, "owner": "willgriffin", "project_status_before_claim": "Review", "runtime": "claude", "schema": "hv-agent-claim:v1", "session": "smrt-2608-resolve-3", "worktree": null}
```

**Comment by willgriffin** [comment]
```json
{"branch": "codex/2608-fk-uuid-text-drift", "claimed_at": "2026-09-02T04:39:52Z", "heartbeat_at": "2026-09-02T04:39:52Z", "lease_seconds": 14400, "owner": "willgriffin", "project_status_before_claim": "Review", "release_evidence_sha256": "0f0b40cad27f458093e83295511396d2cf215eaa7b35a070ea55fbd6ee69028f", "release_message": "Review release for PR #2611 head 2643c9cb3 (merge of origin/main f9fa9b25a into the branch). All five review threads replied to and resolved. Validation: smrt-core 4091 tests, smrt-cli 917 tests, smrt-core... build, pnpm typecheck, biome ci (clean), check:agents-chain, and the live PostgreSQL 17 optional lane including issue-2608-uuid-convergence-postgres.optional.test.ts (6 tests).", "release_pr_heads": {"2611": "2643c9cb3ba68974fccb8dbf31a38296ddb9e4d9"}, "release_reason": "review", "released_at": "2026-09-02T04:40:28Z", "runtime": "claude", "schema": "hv-agent-claim:v1", "session": "smrt-2608-resolve-4", "worktree": "/Users/will/Work/_trees/smrt/fk-uuid-text-drift"}
```

**Comment by willgriffin** [comment]
Review release for PR #2611 head 2643c9cb3 (merge of origin/main f9fa9b25a into the branch). All five review threads replied to and resolved. Validation: smrt-core 4091 tests, smrt-cli 917 tests, smrt-core... build, pnpm typecheck, biome ci (clean), check:agents-chain, and the live PostgreSQL 17 optional lane including issue-2608-uuid-convergence-postgres.optional.test.ts (6 tests).
