### PR TITLE
fix(profiles,users): serialize backfill setup with OIDC provisioning transactions

### LINKED ISSUE #2352: test(profiles): oidc-account-linking "independent DuckDB handles" case fails on GitHub-hosted runners (2/2 runs) — blocks the hosted validation lane
## Context

On 2026-08-17 03:07Z the repo variable `CI_HOSTED_FALLBACK_ENABLED` was set to `true` (#2349, iac#1349 phase 0.5), moving `test-suite.yml` jobs to `ubuntu-latest`. The first hosted full-mode `merge_group` run (31990188105, PR #2344) passed, including `@happyvertical/smrt-profiles#test`. The next two hosted `pull_request_target` runs, on two unrelated PRs, both failed the same single test in `packages/profiles/src/__tests__/oidc-account-linking.test.ts` (~line 684):

> `OIDC Account Linking > createProfileFromOidc > serializes one issuer/subject with different emails across independent DuckDB handles`

This test passes routinely on the metal fleet (`arc-happyvertical-nodocker`, 3 CPU pods) with the same shard shape: `affected-package-tests`, `turbo run test --concurrency=2`, `VITEST_MAX_WORKERS=2`, `NODE_OPTIONS=--max-old-space-size=2048`.

## Evidence

- Run [31990446549](https://github.com/happyvertical/smrt/actions/runs/31990446549/job/95274347400) (branch `fix/issue-2341-template-rewrites`, PR #2348 — diff touches only `packages/core/src/vite-plugin/sveltekit-generator.*`), job `Validate Changes / affected-package-tests (1/3)`: `Error: [vitest-pool]: Worker forks emitted error. Caused by: Error: Worker exited unexpectedly` — silent fork death, no heap/signal line. Last test output before death was that test. 200/208 tests, 15/16 files, `Failed: @happyvertical/smrt-profiles#test`.
- Run [31991297197](https://github.com/happyvertical/smrt/actions/runs/31991297197/job/95275383947) (branch `perf/ui-client-bundle`), job `Validate Changes / affected-package-tests (2/3)`: the same test fails all 3 vitest retries with `DatabaseError: Failed to execute raw query` … `originalError: 'Failed to execute prepared statement'`, `sql: 'SELECT * FROM profiles WHERE id = $1'`. Stack: `@happyvertical/sql/src/duckdb.ts:1125` ← test identity-lookup Proxy (`oidc-account-linking.test.ts:1338`) ← `ProfileCollection.queryRowsWithCache` (`core/src/collection.ts:1325`) ← `ProfileCollection.get` ← `rebindOidcProfileResult` (`src/auth/resolveIdentity.ts:519`) ← `withProvisioningLock` (`src/auth/oidcProvisioningCoordinator.ts:268`). 1 failed / 207 passed.
- This area was stabilised once already: #2172 → PR #2191 (2026-08-02), "serialize row-count observations within caller-owned DuckDB transactions to avoid concurrent queries on one native connection".

## Hypothesis

Not yet confirmed. The test wraps **one** `getDatabase({ type: 'duckdb', url: ':memory:' })` handle in two proxies and runs two `createProfileFromOidc` calls concurrently. `coordinateOidcProvisioning` serialises the provisioning transaction and the post-commit rebind under an `adapter-transaction` lock, but `new BackfillTracker({ db }).initialize()` runs **before** the lock (comment: "Establish the shared backfill table outside the provisioning transaction"), so flow B's DDL/queries can interleave with flow A's transaction and rebind on the same native connection. DuckDB invalidates prepared statements on catalog changes and does not tolerate concurrent statements on one connection — consistent with both `Failed to execute prepared statement` and an outright native abort (the silent fork death). Faster 4-vCPU hosted runners plausibly shift the interleaving enough to hit it reliably where the slower fleet pods mostly don't. Also worth checking: `getDatabase` caches by URL, so vitest retries may reuse a poisoned connection — which would explain 3/3 retry failure.

## Scope

1. Reproduce, e.g. `pnpm --filter @happyvertical/smrt-profiles exec vitest run src/__tests__/oidc-account-linking.test.ts -t "independent DuckDB handles" --repeat 20` on a 4+ core box.
2. Then **either** move the pre-lock `BackfillTracker.initialize()` under the adapter lock for non-Postgres handles (or otherwise make the shared-connection path safe), **or**, if a shared connection across concurrent provisioning flows is not a supported production topology, fix the test to use genuinely serialised access. State which and why.
3. Add a regression guard (repeat/shuffle probe as in #2191).

Not in scope: the hosted lane itself (#2349).

## Acceptance

- 20/20 local repeats green.
- The affected `smrt-profiles` shard green on ≥3 consecutive hosted PR runs.
- #2191-style shuffle probe green.

## Links

- #2349 — hosted-lane trial; this is its first blocker
- #2172 / PR #2191 — prior fix in the same area
- iac#1349 — parent epic
- Job logs: [31990446549](https://github.com/happyvertical/smrt/actions/runs/31990446549/job/95274347400), [31991297197](https://github.com/happyvertical/smrt/actions/runs/31991297197/job/95275383947)

### PR DESCRIPTION
**Pull request by willgriffin**
Closes #2352

## Root cause (verified, not assumed)

The issue's hypothesis is correct, and I confirmed it two ways.

**1. Adapter-level.** The DuckDB adapter guards `transaction()` / `beginTransaction()` with an internal `connectionLock`, but top-level `query()` takes no lock. A statement left in flight when `BEGIN TRANSACTION` runs on the same native connection fails immediately:

```
probe3a commit-then-concurrent-root-reads:  ok            (400 rounds)
probe3b root-stmt-in-flight-at-BEGIN:       FAILED
  sql: 'SELECT 1 FROM t LIMIT 1'
  originalError: 'Failed to execute prepared statement'
```

So concurrent root reads are *not* the hazard (the post-commit rebind's `Promise.all` is fine); a root statement overlapping an open transaction on the same connection is.

**2. In the failing test.** Instrumenting `oidc-account-linking.test.ts` with sub-millisecond start/end markers on the shared root handle shows the exact overlap on this machine, even on a green run:

```
0.265 root start (inflight 1, txdepth 0) SELECT 1 FROM _smrt_backfills LIMIT 1   ← flow A, pre-lock
0.275 root start (inflight 2, txdepth 0) SELECT 1 FROM _smrt_backfills LIMIT 1   ← flow B, pre-lock
0.575 root end   (inflight 1, txdepth 0)
0.800 >>> BEGIN (depth 1, inflight 1)                    ← flow A opens its transaction
0.853 root end   (inflight 0, txdepth 1)                 ← flow B's statement ends INSIDE flow A's transaction
```

`coordinateOidcProvisioning` established the shared `_smrt_backfills` table **before** acquiring its `adapter-transaction` lock ("outside the provisioning transaction"). Both flows therefore issue a root statement while unserialized; whichever flow wins the lock opens `BEGIN TRANSACTION` on the same native connection a few hundred microseconds later, while the other flow's statement is still in flight. The window is ~50µs here, which is why the metal pods mostly get away with it and 4-vCPU hosted runners do not.

Everything else the coordinator does on the root handle — the transaction and the post-commit rebind — was already inside the lock, which is why the reported stack surfaced in `rebindOidcProfileResult`: it is a victim of the poisoned connection, not the cause.

## Fix

Move the tracker initialization inside `withProvisioningLocks`, still outside the provisioning transaction. Every root-handle statement the coordinator owns — tracker setup, the transaction, the post-commit rebind — is now serialized per database URL on SQLite/DuckDB. Transaction-bound callers are unchanged: they still never run `_smrt_backfills` DDL.

`@happyvertical/smrt-profiles` and `@happyvertical/smrt-users` both route through this one coordinator (`@happyvertical/smrt-profiles/internal/oidc-provisioning`), so the single change covers both failing suites — there is no second copy in `smrt-users`. No assertion was weakened: `maxActiveLookups`/`maxActiveResolvers` stay `1` and every row-count assertion is untouched.

Postgres root handles are unaffected in substance: they never take the `adapter-transaction` key, so initialization simply moves under the identity/email locks, and the shared initialization promise makes repeat calls a single cached check.

## Regression guard

`packages/profiles/src/__tests__/oidc-provisioning-coordinator.test.ts` asserts the ordering contract deterministically rather than by racing: it blocks one flow inside its provisioning transaction, starts a second flow, and asserts the second issues **no** statement on the shared DuckDB root handle. Reverting only the fix turns it red with the precise offender:

```
AssertionError: expected [ Array(1) ] to deeply equal []
+ [ "SELECT 1 FROM _smrt_backfills LIMIT 1" ]
```

## Validation

- `@happyvertical/smrt-profiles` full suite — 17 files, **209 passed** (was 208; +1 new test)
- `@happyvertical/smrt-users` — `oidc-provisioning-safety.test.ts` **93 passed**; whole node suite 22 files / **421 passed**. The 7 Svelte component files cannot load in an agent worktree (vite8 + rolldown `Could not resolve 'node:module'`), so CI is the gate for those.
- 20/20 local repeats of `oidc-account-linking.test.ts -t "independent DuckDB handles"`
- 20/20 local repeats of `oidc-provisioning-safety.test.ts -t "one DuckDB root handle"`
- #2191-style `--sequence.shuffle` probe: 6/6 green on each OIDC file (43 and 93 tests)
- `pnpm typecheck` (profiles, users), `biome check` on touched files, `pnpm check:agents-chain`, `pnpm smrt dev:knowledge-check` — clean
- The real acceptance test is this PR's own hosted `affected-package-tests` shards.

No changeset is committed — release automation generates them on merge.

---

## Update: hosted CI found a second, dominant hazard

Run [31994388100](https://github.com/happyvertical/smrt/actions/runs/31994388100) on `5edce0dbd` (lock-ordering fix only) shows the fix above was **necessary but not sufficient**:

- shard 3/3 — green
- shard 1/3 — `@happyvertical/smrt-users#test`, all 3 retries, `Failed to execute raw query` at `UserCollection.ts:726` inside `withProvisioningLock`
- shard 2/3 — `@happyvertical/smrt-profiles#test`, silent worker abort (16/17 files, 201/209 tests) — the issue's other reported signature

Both failures are *inside* the coordinator lock, where no other flow can run. So the remaining overlap is a flow racing **itself**: `rebindOidcProvisioningResult` / `rebindOidcProfileResult` issued their two or three primary-key reads through `Promise.all` on one native DuckDB connection. That is why the originally reported profiles stack pointed at `SELECT * FROM profiles WHERE id = $1` in the rebind — it was the direct cause, not a downstream victim. My local probe passed 400 rounds of that shape on macOS/arm64; the hosted x86 runners do not tolerate it.

**Second fix** (`c7bca9561`): the rebind reads and the `LIMIT 2` owner/email candidate reads are now sequential in both packages. They are primary-key lookups — one or two extra round trips on a first login, immaterial on pooled Postgres.

**Second guard**: `never overlaps two statements on one shared DuckDB connection during concurrent provisioning` counts in-flight statements across the root handle *and* its transaction handle while two real `createProfileFromOidc` flows run. It fails on structure, not on a race — restoring either `Promise.all` turns it red naming the duplicated statement:

```
AssertionError: expected [ …(2) ] to deeply equal []
+ "SELECT * FROM oidc_identities WHERE id = $1",
+ "SELECT * FROM oidc_identities WHERE id = $1",
```

This guard would have caught the original defect on any machine, which the timing-dependent suites could not.

**Revalidation:** profiles 17 files / 210 passed; users node suite 22 files / 421 passed (7 Svelte files need CI — vite8+rolldown cannot load the plugin in an agent worktree); 20/20 repeats of the users DuckDB test; 6/6 shuffle on the guard file; typecheck, biome, agents-chain, knowledge-check clean.

```json
{"schema":"hv-agent-run:v1","policy_revision":"1.0.0","runtime":"claude","session":"bb4c7a21-74b8-4fce-972c-107c341951d9","issue":"https://github.com/happyvertical/smrt/issues/2352"}
```

### CODE REVIEW

File: packages/profiles/src/__tests__/oidc-provisioning-coordinator.test.ts [hunk 1]
```diff
@@ -0,0 +1,131 @@
...
+        firstTransactionOpen.resolve();
+        await releaseFirstTransaction.promise;
+        return 'first';
+      });
+      await firstTransactionOpen.promise;
+
+      // The second flow must block on the adapter lock rather than touch the
+      // connection the first flow's transaction owns.
+      second = coordinate('identity:second', async () => 'second');
+      await settleEventLoop();
```
[the remark this answers is not in the document]
Comment (willgriffin) [reply packages/profiles/src/__tests__/oidc-provisioning-coordinator.test.ts:126]: Fixed in 5edce0dbd. Both flows are now marked handled at creation, and the first flow is raced against its own transaction-open signal so an early failure reports that failure instead of timing out. Verified against the deliberately reverted fix: the red path now emits only `AssertionError: expected [ Array(1) ] to deeply equal []` naming `SELECT 1 FROM _smrt_backfills LIMIT 1`, with no Unhandled Errors section.
