### ISSUE TITLE
test(profiles): oidc-account-linking "independent DuckDB handles" case fails on GitHub-hosted runners (2/2 runs) — blocks the hosted validation lane

### ISSUE THREAD

**Issue by willgriffin** [happyvertical/smrt#2352]
## Context

On 2026-08-17 03:07Z the repo variable `CI_HOSTED_FALLBACK_ENABLED` was set to `true` (#2349, iac#1349 phase 0.5), moving `test-suite.yml` jobs to `ubuntu-latest`. The first hosted full-mode `merge_group` run (31990188105, PR #2344) passed, including `@happyvertical/smrt-profiles#test`. The next two hosted `pull_request_target` runs, on two unrelated PRs, both failed the same single test in `packages/profiles/src/__tests__/oidc-account-linking.test.ts` (~line 684):

> `OIDC Account Linking > createProfileFromOidc > serializes one issuer/subject with different emails across independent DuckDB handles`

This test passes routinely on the metal fleet (`arc-happyvertical-nodocker`, 3 CPU pods) with the same shard shape: `affected-package-tests`, `turbo run test --concurrency=2`, `VITEST_MAX_WORKERS=2`, `NODE_OPTIONS=--max-old-space-size=2048`.

## Evidence

- Run [31990446549](https://github.com/happyvertical/smrt/actions/runs/31990446549/job/95274347400) (branch `fix/issue-2341-template-rewrites`, PR #2348 — diff touches only `packages/core/src/vite-plugin/sveltekit-generator.*`), job `Validate Changes / affected-package-tests (1/3)`: `Error: [vitest-pool]: Worker forks emitted error. Caused by: Error: Worker exited unexpectedly` — silent fork death, no heap/signal line. Last test output before death was that test. 200/208 tests, 15/16 files, `Failed: @happyvertical/smrt-profiles#test`.
- Run [31991297197](https://github.com/happyvertical/smrt/actions/runs/31991297197/job/95275383947) (branch `perf/ui-client-bundle`), job `Validate Changes / affected-package-tests (2/3)`: the same test fails all 3 vitest retries with `DatabaseError: Failed to execute raw query` … `originalError: 'Failed to execute prepared statement'`, `sql: 'SELECT * FROM profiles WHERE id = $1'`. Stack: `@happyvertical/sql/src/duckdb.ts:1125` ← test identity-lookup Proxy (`oidc-account-linking.test.ts:1338`) ← `ProfileCollection.queryRowsWithCache` (`core/src/collection.ts:1325`) ← `ProfileCollection.get` ← `rebindOidcProfileResult` (`src/auth/resolveIdentity.ts:519`) ← `withProvisioningLock` (`src/auth/oidcProvisioningCoordinator.ts:268`). 1 failed / 207 passed.
- This area was stabilised once already: #2172 → PR #2191 (2026-08-02), "serialize row-count observations within caller-owned DuckDB transactions to avoid concurrent queries on one native connection".

## Hypothesis

Not yet confirmed. The test wraps **one** `getDatabase({ type: 'duckdb', url: ':memory:' })` handle in two proxies and runs two `createProfileFromOidc` calls concurrently. `coordinateOidcProvisioning` serialises the provisioning transaction and the post-commit rebind under an `adapter-transaction` lock, but `new BackfillTracker({ db }).initialize()` runs **before** the lock (comment: "Establish the shared backfill table outside the provisioning transaction"), so flow B's DDL/queries can interleave with flow A's transaction and rebind on the same native connection. DuckDB invalidates prepared statements on catalog changes and does not tolerate concurrent statements on one connection — consistent with both `Failed to execute prepared statement` and an outright native abort (the silent fork death). Faster 4-vCPU hosted runners plausibly shift the interleaving enough to hit it reliably where the slower fleet pods mostly don't. Also worth checking: `getDatabase` caches by URL, so vitest retries may reuse a poisoned connection — which would explain 3/3 retry failure.

## Scope

1. Reproduce, e.g. `pnpm --filter @happyvertical/smrt-profiles exec vitest run src/__tests__/oidc-account-linking.test.ts -t "independent DuckDB handles" --repeat 20` on a 4+ core box.
2. Then **either** move the pre-lock `BackfillTracker.initialize()` under the adapter lock for non-Postgres handles (or otherwise make the shared-connection path safe), **or**, if a shared connection across concurrent provisioning flows is not a supported production topology, fix the test to use genuinely serialised access. State which and why.
3. Add a regression guard (repeat/shuffle probe as in #2191).

Not in scope: the hosted lane itself (#2349).

## Acceptance

- 20/20 local repeats green.
- The affected `smrt-profiles` shard green on ≥3 consecutive hosted PR runs.
- #2191-style shuffle probe green.

## Links

- #2349 — hosted-lane trial; this is its first blocker
- #2172 / PR #2191 — prior fix in the same area
- iac#1349 — parent epic
- Job logs: [31990446549](https://github.com/happyvertical/smrt/actions/runs/31990446549/job/95274347400), [31991297197](https://github.com/happyvertical/smrt/actions/runs/31991297197/job/95275383947)

**Comment by willgriffin** [comment]
Same run (31991297197), a second package hits the same class of failure on hosted:

- `Validate Changes / affected-package-tests (3/3)` — https://github.com/happyvertical/smrt/actions/runs/31991297197/job/95275383932 — `@happyvertical/smrt-users#test`: `src/__tests__/oidc-provisioning-safety.test.ts > safe OIDC provisioning > serializes unrelated first logins on one DuckDB root handle` fails all 3 retries.

So this is not profiles-only: both OIDC provisioning paths that share one native DuckDB root handle across concurrent flows trip on hosted. Scope the fix (or the shared-connection guard) to cover `smrt-users` as well; acceptance should include that test's ≥3 green hosted shards too.

**Comment by willgriffin** [comment]
```json
{"branch": "fix/issue-2352-oidc-duckdb-shared-handle", "claimed_at": "2026-08-17T03:56:28.422874Z", "heartbeat_at": "2026-08-17T03:56:28.422924Z", "lease_seconds": 14400, "owner": "willgriffin", "runtime": "claude", "schema": "hv-agent-claim:v1", "session": "bb4c7a21-74b8-4fce-972c-107c341951d9", "worktree": "/Users/will/Work/happyvertical/repos/smrt/.claude/worktrees/agent-ad09b267baba9435d"}
```

**Comment by willgriffin** [comment]
Implementation claim released by `claude` session `bb4c7a21-74b8-4fce-972c-107c341951d9` (review).

**Comment by willgriffin** [comment]
```json
{"branch": "fix/issue-2352-oidc-duckdb-shared-handle", "claimed_at": "2026-08-17T04:23:23Z", "heartbeat_at": "2026-08-17T04:23:23Z", "lease_seconds": 14400, "owner": "willgriffin", "project_status_before_claim": "Review", "release_evidence_sha256": "3b3f12f7530f795b4e65c6a840203123c1fc6b5224a82440cafd715523f73944", "release_message": "Implementation claim released by `claude` session `bb4c7a21-74b8-4fce-972c-107c341951d9` (review).", "release_pr_heads": {"2353": "5edce0dbdf7af8eefedc2a22f4df976d57702f21"}, "release_reason": "review", "released_at": "2026-08-17T04:25:14Z", "runtime": "claude", "schema": "hv-agent-claim:v1", "session": "bb4c7a21-74b8-4fce-972c-107c341951d9", "worktree": "/Users/will/Work/happyvertical/repos/smrt/.claude/worktrees/agent-ad09b267baba9435d"}
```

**Comment by willgriffin** [comment]
Implementation claim released by `claude` session `bb4c7a21-74b8-4fce-972c-107c341951d9` (review).

**Comment by willgriffin** [comment]
Status after PR #2353's own hosted run ([31994388100](https://github.com/happyvertical/smrt/actions/runs/31994388100)): the pre-lock backfill race is real and #2353 removes it (instrumented, deterministic guard test), **but the same test still killed its worker on hosted** — `affected-package-tests (2/3)`, `@happyvertical/smrt-profiles#test`, 16/17 files, `Worker exited unexpectedly`, no JS error, last output = `serializes one issuer/subject with different emails across independent DuckDB handles`. So there is a second failure mode: a native abort, not a prepared-statement error, and it survives serialising the coordinator's own statements.

Candidates to check next (all pre-coordinator or outside it): concurrent `Collection.create()`/runtime initialisation (schema verify / DDL) issued by `createProfileFromOidc` on both proxied handles before `coordinateOidcProvisioning` runs; the test's `withIdentityLookupObserver` proxy re-entering `query` during `observe()`; DuckDB `:memory:` handle caching by URL. The durable fix for the whole class is probably in `@happyvertical/sql`'s DuckDB adapter (it locks `transaction()`/`beginTransaction()` on `connectionLock` but not top-level `query()`), which would make any shared-root-handle topology safe rather than each caller re-implementing serialisation.

Getting the child's signal is the missing evidence: on hosted, run the file with core dumps enabled (`ulimit -c unlimited`, `NODE_OPTIONS=--report-on-signal`), or a `workflow_dispatch` diagnostic on the branch that uploads the core / `report.*.json`. Not reproducible on macOS (20/20 green).

`CI_HOSTED_FALLBACK_ENABLED` was set back to `false` at 04:36:25Z so unrelated PRs and merge groups stop paying for this; the hosted lane (#2349) stays parked on this issue. #2353 remains open as a correct partial fix — decide whether to land it as-is (it fixes a real race and adds the guard) and continue here, or extend it.

**Comment by willgriffin** [comment]
```json
{"branch": "fix/issue-2352-oidc-duckdb-shared-handle", "claimed_at": "2026-08-17T04:42:54.511056Z", "heartbeat_at": "2026-08-17T04:42:54.511140Z", "lease_seconds": 14400, "owner": "willgriffin", "project_status_before_claim": "Review", "runtime": "claude", "schema": "hv-agent-claim:v1", "session": "bb4c7a21-74b8-4fce-972c-107c341951d9", "worktree": "/Users/will/Work/happyvertical/repos/smrt/.claude/worktrees/agent-ad09b267baba9435d"}
```

**Comment by willgriffin** [comment]
Decisive evidence from #2353's own hosted run ([job 95284386161](https://github.com/happyvertical/smrt/actions/runs/31994388100/job/95284386161), `smrt-users`, 3/3 retries): the failing `SELECT` is the post-commit rebind (`UserCollection.ts:726` → `ProfileCollection.get` / `UserCollection.get`) **inside `withProvisioningLock`**. The victim is under the lock, so the offender is a statement the concurrent flow issues *outside the coordinator* — pre-coordinator lookups and `Collection.create()` runtime initialisation in `UserCollection.ts` / `resolveIdentity.ts` — which lands inside the first flow's open transaction on the one native connection.

Root of the class is in `@happyvertical/sql`'s DuckDB adapter (`packages/sql/src/duckdb.ts`): it returns `url` (so smrt's `adapter-transaction` lock keys correctly), and `transaction()` holds `connectionLock` across BEGIN…COMMIT — but top-level `query()` does not take that lock, so any root-handle statement can interleave with an open transaction. SQLite's adapter chains every statement per handle; DuckDB's should do the same (`query()` on the connection chain, with the transaction scope's own `tx.query` staying inside the held lock). Every caller-side serialisation (#2191, #2353) is a partial workaround for that gap.

Proposed split:
1. **sdk**: serialise DuckDB `query()` on the per-connection lock (watch for root-`db.query` used *inside* a `db.transaction` callback — that pattern would deadlock; audit for it).
2. **smrt (#2353)**: keep the coordinator fix + guard (real, independent race), and additionally take the non-Postgres adapter lock at the provisioning entry points so the shared-root-handle topology is safe before the sdk release lands. Both OIDC tests are then hosted-safe by construction, and the native abort — DuckDB under concurrent statements — should disappear with the interleaving.

**Comment by willgriffin** [comment]
Implementation claim released by `claude` session `bb4c7a21-74b8-4fce-972c-107c341951d9` (review).

**Comment by willgriffin** [comment]
Hosted verification of PR #2353's final head `c7bca9561`: run [31995739974 attempt 2](https://github.com/happyvertical/smrt/actions/runs/31995739974/attempts/2) (05:26–05:40Z, lever opened for exactly this rerun and closed after) — `affected-package-tests` **1/3, 2/3, 3/3 all green on `ubuntu-latest`** (381–394 s each). Correction to the PR write-up: attempt 1 of that run (04:48Z) was on `arc-happyvertical-nodocker`, not hosted, so attempt 2 is the first real hosted pass of the final head.

Where that leaves the analysis: with the coordinator lock covering backfill init and the rebind/candidate reads made sequential, two real flows over one DuckDB root handle produce no overlapping statements (the new in-flight-statement guard asserts that structurally), and both failure modes — prepared-statement error and the silent worker abort — were absent on hosted. The earlier "offender is pre-coordinator" reading in this thread was wrong; the overlap was the flow racing itself in `Promise.all` rebinds. The sdk-side observation stands as hardening (DuckDB adapter `query()` is unlocked while `transaction()` is locked), but it is no longer required to close this issue.

Acceptance count: 1 of the ≥3 consecutive hosted-green runs on the final head. The merge-group transit (if the lever is on then) or two further hosted reruns would complete it.
